# Generated by Django 6.0.2 on 2026-02-17 10:44

import django.db.models.deletion
import django.utils.timezone
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('category_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], default='Bronze', max_length=50)),
                ('contract_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('specialty', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_issues_assigned', models.IntegerField(default=0)),
                ('resolved_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(default=tickets.models.generate_ticket_code, editable=False, max_length=6, unique=True)),
                ('submitter_name', models.CharField(max_length=255)),
                ('submission_source', models.CharField(choices=[('Website', 'Website'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('Phone', 'Phone')], default='Website', max_length=20)),
                ('issue_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network')], max_length=50)),
                ('description', models.TextField()),
                ('contact_number', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.member')),
                ('org_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.clientcompany')),
            ],
        ),
    ]
